eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads
spring:
  datasource:
    url: jdbc:mysql://10.48.172.10:3306/cloud?useUnicode=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: sjzhou
    password: sjzhou2018
    max-idle: 10
    min-idle: 5
    test-on-borrow: false
    time-between-eviction-runs-millis: 18800
    test-while-idle: true
    validation-query: SELECT 1
    hikari:
      minimum-idle: 0
  redis:
    host: 10.48.172.10
    port: 6379
    password: 

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: abc
    password: 123
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
redis:
  cache:
    expiration: 3601
ribbon:
  eager-load:
    enabled: true
    clients: panda-auth,panda-user-service
  Httpclient:
    enabled: true
  OkHttp:
    enabled: false
  ReadTimeout: 10000
  ConnectTimeout: 10000

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: false
  httpclient:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
